const $ = s => document.querySelector(s);
const enc = new TextEncoder();
const bytes = text => enc.encode(text).length;
const MODELS = {
 mini: {name:'KiwiGPT Mini',short:'Mini',id:'Qwen2.5-0.5B-Instruct-q4f32_1-MLC',detail:'Leicht und schnell',memory:'ungefähr 1,1 GB'},
 middle: {name:'KiwiGPT Mittel',short:'Mittel',id:'Qwen2.5-1.5B-Instruct-q4f32_1-MLC',detail:'Ausgewogen für normale Aufgaben',memory:'ungefähr 1,9 GB'},
 max: {name:'KiwiGPT Max',short:'Max',id:'Qwen2.5-3B-Instruct-q4f32_1-MLC',detail:'Stärker für schwierige Aufgaben',memory:'ungefähr 2,9 GB'}
};
let engine, worker, loadPromise, activeModel, busy = false, loading = false, stopped = false, attachment = null, recognition;
let selectedModel = localStorage.getItem('kiwigpt-model') in MODELS ? localStorage.getItem('kiwigpt-model') : 'middle';
let chats = [], currentId, voiceConsent = false;
try { const saved = JSON.parse(localStorage.getItem('kiwigpt-chats') || localStorage.getItem('aii-chats') || '[]'); if (Array.isArray(saved)) chats = saved.filter(c => typeof c.id === 'string' && typeof c.title === 'string' && Array.isArray(c.messages)).map(c => ({...c,messages:c.messages.filter(m=>['user','assistant'].includes(m.role)&&typeof m.content==='string')})); } catch {}
const current = () => chats.find(c => c.id === currentId);
function notice(text) { $('#notice').textContent = text; $('#notice').hidden = !text; }
function save() { try { localStorage.setItem('kiwigpt-chats', JSON.stringify(chats)); } catch { notice('Der Browserspeicher ist voll oder gesperrt. Exportiere deine Chats, bevor du diese Seite schließt.'); } }
function closeSidebar() { document.body.classList.remove('sidebar-open'); $('#scrim').hidden = true; $('#menu').setAttribute('aria-expanded','false'); }
function newChat() { if (busy) return; currentId = crypto.randomUUID(); chats.unshift({id:currentId,title:'Neuer Chat',messages:[]}); render(); closeSidebar(); $('#prompt').focus(); }
function renderHistory() { const nav = $('#history'); nav.replaceChildren(); const query = $('#search').value.toLocaleLowerCase(); const items = chats.filter(c => c.messages.length && c.title.toLocaleLowerCase().includes(query)); if (!items.length) { const p=document.createElement('p');p.className='empty-history';p.textContent=query?'Keine passenden Chats.':'Hier ist Platz für deine Gedanken.';nav.append(p); } items.forEach(c=>{const b=document.createElement('button');b.className='history-item'+(c.id===currentId?' active':'');b.textContent=c.title;b.title=c.title;b.disabled=busy;b.onclick=()=>{currentId=c.id;attachment=null;renderAttachment();render();closeSidebar();};nav.append(b);}); }
function richText(el, text) { el.replaceChildren(); const parts = text.split('```'); parts.forEach((part,i)=>{if(i%2){const pre=document.createElement('pre'),code=document.createElement('code');code.textContent=part.replace(/^[\w+-]*\n/,'');pre.append(code);el.append(pre);}else{el.append(document.createTextNode(part));}}); }
function speak(text) { if(!('speechSynthesis' in window)){notice('Vorlesen wird in diesem Browser nicht unterstützt.');return;} speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';speechSynthesis.speak(u); }
function renderMessages() { const list=$('#messages');list.replaceChildren();const messages=current()?.messages||[];$('#welcome').hidden=messages.length>0;$('.compose-wrap').classList.toggle('empty',messages.length===0);messages.forEach((m,i)=>{const article=document.createElement('article');article.className='message '+m.role;if(m.role==='assistant'){const label=document.createElement('div');label.className='message-label';label.textContent='KiwiGPT';article.append(label);}const body=document.createElement('div');body.className='message-body';richText(body,m.content);article.append(body);if(m.role==='assistant'&&m.content&&!busy){const actions=document.createElement('div');actions.className='message-actions';const copy=document.createElement('button');copy.textContent='Kopieren';copy.onclick=async()=>{try{await navigator.clipboard.writeText(m.content);copy.textContent='Kopiert';}catch{notice('Kopieren ist nicht erlaubt. Markiere den Text zum Kopieren.');}};const read=document.createElement('button');read.textContent='Vorlesen';read.onclick=()=>speak(m.content);actions.append(copy,read);if(i===messages.length-1){const retry=document.createElement('button');retry.textContent='Neu antworten';retry.onclick=()=>generate(true);actions.append(retry);}article.append(actions);}list.append(article);}); }
function render() { renderHistory();renderMessages(); if(!busy&&current()?.messages.at(-1)?.role==='user'){const retry=document.createElement('button');retry.className='secondary';retry.textContent='Antwort erneut versuchen';retry.onclick=()=>generate(true);$('#messages').append(retry);} }
function setBusy(value) { busy=value;$('#new-chat').disabled=value;$('#mode').disabled=value;$('#model-choice').disabled=value||loading;$('#attach').disabled=value;$('#mic').disabled=value;$('#delete-chat').disabled=value;$('#send').setAttribute('aria-label',value?'Antwort stoppen':'Nachricht senden');$('#send').innerHTML=value?'<span class="stop-square"></span>':'<svg><use href="#i-arrow"/></svg>';renderHistory(); }
function scrollBottom() { $('#conversation').scrollTop=$('#conversation').scrollHeight; }
function confirmAction(title,text){return new Promise(resolve=>{const d=$('#confirm');$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;let settled=false;const finish=v=>{if(settled)return;settled=true;d.close();resolve(v);};$('#confirm-no').onclick=()=>finish(false);$('#confirm-yes').onclick=()=>finish(true);d.oncancel=e=>{e.preventDefault();finish(false);};d.showModal();});}
function updateModelUI() { const model=MODELS[selectedModel];$('#model-choice').value=selectedModel;$('#model-name').textContent=model.short;$('#settings-model-name').textContent=model.name;$('#settings-model-detail').textContent=model.detail;$('#footer-model').textContent=model.name;$('#load-model').textContent=activeModel===selectedModel?model.name+' ist bereit':model.name+' jetzt herunterladen';if(!loading)$('#model-status').textContent=activeModel===selectedModel?model.short+' · bereit':model.short+' · wartet';if(!loading)$('#load-detail').textContent=model.name+' benötigt '+model.memory+' Grafikspeicher. Ein WebGPU-fähiger Browser ist erforderlich.';$('#status-dot').classList.toggle('ready',activeModel===selectedModel); }
async function loadModel() {
 if(activeModel===selectedModel&&engine)return engine;if(loadPromise)return loadPromise;
 const target=selectedModel,model=MODELS[target];
 loadPromise=(async()=>{let failure;loading=true;$('#model-choice').disabled=true;$('#load-model').disabled=true;$('#load-progress').hidden=false;$('#model-status').textContent=model.short+' · lädt';
 try {
  if(!navigator.gpu)throw new Error('WebGPU ist hier nicht verfügbar. Öffne KiwiGPT in einem aktuellen WebGPU-fähigen Browser auf einem unterstützten Gerät.');
  const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw new Error('Keine kompatible GPU gefunden. Versuche ein anderes Gerät oder aktiviere die Hardwarebeschleunigung.');
  const progress=p=>{const value=Math.max(0,Math.min(1,p.progress||0));$('#load-progress').value=value;$('#load-detail').textContent=p.text;$('#model-status').textContent=`${model.short} · ${Math.round(value*100)} %`;};
  if(engine){worker?.terminate();worker=null;engine=null;activeModel=null;}
  const {CreateWebWorkerMLCEngine}=await import('https://esm.run/@mlc-ai/web-llm@0.2.79');worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});engine=await CreateWebWorkerMLCEngine(worker,model.id,{initProgressCallback:progress});
  activeModel=target;notice('');return engine;
 } catch(e) {failure=e;if(!activeModel){worker?.terminate();worker=null;engine=null;}notice('Modelldownload fehlgeschlagen. Öffne die Modelleinstellungen für Details.');throw e;
 } finally {loading=false;loadPromise=null;$('#load-progress').hidden=true;$('#load-model').disabled=false;$('#model-choice').disabled=busy;updateModelUI();if(failure){$('#model-status').textContent=model.short+' · Fehler';$('#load-detail').textContent='Das Modell konnte nicht gestartet werden: '+failure.message;}}
 })();return loadPromise;
}
const MODES={fast:{tokens:192,instruction:'Antworte kurz und direkt in höchstens drei Sätzen.'},balanced:{tokens:512,instruction:'Antworte verständlich mit passenden Details und kurzen Absätzen.'},deep:{tokens:768,instruction:'Beantworte die Frage sorgfältig. Nenne relevante Annahmen und Unsicherheiten. Gib eine klare Lösung.'}};
function contextMessages(messages,system) { let remaining=2600-bytes(system),chosen=[];for(let i=messages.length-1;i>=0;i--){const m=messages[i];if(!m.content)continue;const cost=bytes(m.content)+24;if(cost>remaining)break;chosen.unshift({role:m.role,content:m.content});remaining-=cost;}while(chosen.length&&chosen[0].role!=='user')chosen.shift();if(!chosen.length)throw new Error('Diese Nachricht ist zu lang für das kleine Modell. Bitte kürze sie auf etwa 1.500 Zeichen.');return [{role:'system',content:system},...chosen]; }
async function generate(regenerate=false) {
 if(busy){stopped=true;engine?.interruptGenerate();return;}
 if(activeModel!==selectedModel||!engine){notice(MODELS[selectedModel].name+' wird geladen. Deine Nachricht bleibt erhalten.');try{await loadModel();}catch{return;}}
 const chat=current();let input=$('#prompt').value.trim();
 if(!regenerate){if(!input&&!attachment)return;input+=(attachment?'\n\nTextdatei '+attachment.name+':\n'+attachment.text:'');if(bytes(input)>2000){notice('Die Nachricht mit Anhang ist zu lang. Bitte auf höchstens 2.000 UTF-8-Bytes kürzen (ungefähr 1.500–2.000 Zeichen).');return;}chat.messages.push({role:'user',content:input});chat.title=chat.messages.find(m=>m.role==='user').content.slice(0,45);$('#prompt').value='';$('#prompt').style.height='auto';attachment=null;renderAttachment();}
 else if(chat.messages.at(-1)?.role==='assistant'){chat.messages.pop();}
 const history=chat.messages.slice();const mode=MODES[$('#mode').value];const deep=$('#mode').value==='deep';const reply={role:'assistant',content:''};chat.messages.push(reply);stopped=false;notice('');setBusy(true);renderMessages();save();scrollBottom();const body=$('#messages').lastElementChild.querySelector('.message-body');body.textContent='KiwiGPT antwortet …';
 try {
  const system='Du bist KiwiGPT, ein hilfreicher lokaler KI-Assistent. Antworte in der Sprache des Nutzers, standardmäßig Deutsch. Erfinde keine Fähigkeiten, Quellen oder Fakten. '+mode.instruction;
  const prompt=contextMessages(history,system);let draft='';
  const stream=await engine.chat.completions.create({messages:prompt,max_tokens:mode.tokens,temperature:deep?0.35:0.65,stream:true});
  for await(const chunk of stream){draft+=chunk.choices[0]?.delta?.content||'';if(!deep||stopped){reply.content=draft;richText(body,draft);}else body.textContent='Antwort wird vorbereitet …';scrollBottom();if(stopped)break;}
  if(deep&&!stopped&&draft){body.textContent='Antwort wird geprüft …';const question=history.at(-1).content;const reviewSystem='Du bist KiwiGPT. Prüfe den Entwurf auf sachliche Fehler und beantworte die Frage auf Deutsch. Gib nur die verbesserte finale Antwort aus. Behaupte keine externe Faktenprüfung.';let shortDraft=draft;while(bytes(question)+bytes(shortDraft)+bytes(reviewSystem)>2500)shortDraft=shortDraft.slice(0,-80);const review=await engine.chat.completions.create({messages:[{role:'system',content:reviewSystem},{role:'user',content:'Frage: '+question+'\nEntwurf: '+shortDraft}],max_tokens:768,temperature:0.3,stream:true});for await(const chunk of review){reply.content+=chunk.choices[0]?.delta?.content||'';richText(body,reply.content);scrollBottom();if(stopped)break;}}
  else reply.content=draft;
  if(!reply.content){chat.messages.pop();notice(stopped?'Antwort gestoppt.':'Das Modell hat keine Antwort geliefert. Versuche eine kürzere Frage.');}else if(stopped)notice('Antwort gestoppt.');
  if(!stopped&&reply.content&&$('#read-aloud').checked)speak(reply.content);
 } catch(e) {if(!reply.content)chat.messages.pop();notice('Keine vollständige Antwort: '+e.message+' Versuche eine kürzere Frage oder lade die Seite neu.');}
 finally {setBusy(false);save();render();scrollBottom();}
}
function renderAttachment(){const el=$('#attachment');el.replaceChildren();el.hidden=!attachment;if(attachment){const text=document.createElement('span');text.textContent='Textdatei: '+attachment.name;const remove=document.createElement('button');remove.textContent='Entfernen';remove.onclick=()=>{attachment=null;renderAttachment();};el.append(text,remove);}}
$('#composer').onsubmit=e=>{e.preventDefault();generate();};$('#prompt').oninput=()=>{const el=$('#prompt');el.style.height='auto';el.style.height=Math.min(el.scrollHeight,180)+'px';if(el.value.trim()&&!engine&&!loading)loadModel().catch(()=>{});};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&matchMedia('(min-width:761px)').matches){e.preventDefault();generate();}};
$('#new-chat').onclick=newChat;$('#search').oninput=renderHistory;
$('#menu').onclick=()=>{if(matchMedia('(max-width:760px)').matches){const open=document.body.classList.toggle('sidebar-open');$('#scrim').hidden=!open;$('#menu').setAttribute('aria-expanded',String(open));if(open)$('#close-sidebar').focus();}else{document.body.classList.toggle('sidebar-hidden');$('#menu').setAttribute('aria-expanded',String(!document.body.classList.contains('sidebar-hidden')));}};
$('#close-sidebar').onclick=closeSidebar;$('#scrim').onclick=closeSidebar;
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();newChat();}});
for(const id of ['settings-open','model-open','status-open','about'])$('#'+id).onclick=()=>$('#settings').showModal();$('#load-model').onclick=()=>loadModel().catch(()=>{});
$('#model-choice').onchange=e=>{selectedModel=e.target.value;localStorage.setItem('kiwigpt-model',selectedModel);updateModelUI();loadModel().catch(()=>{});};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.prompt;$('#prompt').dispatchEvent(new Event('input'));$('#prompt').focus();});
$('#attach').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>1600){notice('Bitte eine kleine Textdatei mit höchstens 1.600 Bytes auswählen. Größere Dokumente passen nicht in den Kontext.');return;}if(!/\.(txt|md|csv|json)$/i.test(file.name)){notice('Unterstützt werden TXT, Markdown, CSV und JSON.');return;}try{attachment={name:file.name,text:await file.text()};renderAttachment();notice('');}catch{notice('Die Datei konnte nicht gelesen werden.');}};
$('#mic').onclick=async()=>{const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){notice('Diktieren ist in diesem Browser nicht verfügbar. Nutze alternativ das Mikrofon deiner Tastatur.');return;}if(recognition){recognition.stop();return;}if(!voiceConsent){voiceConsent=await confirmAction('Diktieren aktivieren?','Die Spracherkennung deines Browsers kann deine Audioaufnahme an seinen Anbieter senden. Dies ist nicht zwingend lokal. Fortfahren?');if(!voiceConsent)return;}try{recognition=new Speech();recognition.lang='de-DE';recognition.interimResults=false;recognition.onresult=e=>{$('#prompt').value+=($('#prompt').value?' ':'')+e.results[0][0].transcript;$('#prompt').dispatchEvent(new Event('input'));};recognition.onerror=e=>notice('Diktieren nicht möglich: '+e.error);recognition.onend=()=>{recognition=null;$('#mic').setAttribute('aria-label','Nachricht diktieren');$('#mic').style.color='';};recognition.start();$('#mic').style.color='#b7d0bd';$('#mic').setAttribute('aria-label','Diktieren stoppen');notice('Mikrofon aktiv. Sprich deine Nachricht. Sie wird nicht automatisch gesendet.');}catch(e){recognition=null;notice(e.message);}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(chats.filter(c=>c.messages.length),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kiwigpt-chats.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#delete-chat').onclick=async()=>{if(busy)return;if(await confirmAction('Chat löschen?','Dieser Chat wird aus diesem Browser gelöscht. Das kann nicht rückgängig gemacht werden.')){chats=chats.filter(c=>c.id!==currentId);newChat();save();$('#settings').close();}};
$('#read-aloud').onchange=()=>{if(!$('#read-aloud').checked)window.speechSynthesis?.cancel();};
updateModelUI();currentId=chats.find(c=>c.messages.length)?.id;if(!currentId)newChat();else render();
if(!navigator.gpu){$('#model-status').textContent='WebGPU erforderlich';$('#load-detail').textContent='Dieser Browser stellt kein WebGPU bereit. Ein unterstützter Browser und ein kompatibles Gerät sind für die lokale KI nötig.';}
const lifecycle=new AbortController();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'stage_kiwigpt_message',title:'Nachricht in KiwiGPT vorbereiten',description:'Trägt Text ins sichtbare Eingabefeld ein und startet den lokalen Modelldownload. Sendet die Nachricht nicht.',inputSchema:{type:'object',properties:{text:{type:'string',maxLength:1500}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.text!=='string'||input.text.length>1500||Object.keys(input).some(k=>k!=='text'))throw new Error('Ein Text mit höchstens 1.500 Zeichen ist erforderlich.');if(busy)throw new Error('KiwiGPT antwortet noch.');$('#prompt').value=input.text;$('#prompt').dispatchEvent(new Event('input'));return {staged:true,text:$('#prompt').value,model:MODELS[selectedModel].name};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
window.addEventListener('pagehide',()=>{lifecycle.abort();worker?.terminate();window.speechSynthesis?.cancel();recognition?.stop();});
